name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build_and_test:
    name: build and test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build and test
      working-directory: ./bugreport
      run: | 
        mvn -B package --file pom.xml  
       
       
  publish: 
    needs: build_and_test
    runs-on: ubuntu-latest
    name: publish bugger page
    
    steps:
    - name: Check out buggerpage
      uses: Bhacaz/checkout-files@v1
      with: 
        files: ./buggerpage
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/buggerpage:latest
      
    
